# Generated by Django 3.2 on 2022-12-16 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='name',
            old_name='age',
            new_name='ages',
        ),
    ]
